# -*- coding: utf-8 -*-
"""Course_Registration1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWsVPHzPQplJR1hcDy_x0EIfVWfUm08D
"""

import csv
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, student_id, name):
        self._student_id = student_id
        self._name = name

    @abstractmethod
    def display(self):
        pass

class Student(Person):
    def __init__(self, student_id, name):
        super().__init__(student_id, name)

    def display(self):
        print(self._student_id, self._name)

class Course:
    def __init__(self, course_id, course_name, credits):
        self._course_id = course_id
        self._course_name = course_name
        self._credits = credits

    def display(self):
        print(self._course_id, self._course_name, self._credits)

class CourseSystem:
    def __init__(self):
        self.students = []
        self.courses = []
        self.registrations = []


    students_file = '/students_large.csv'
    courses_file = '/courses_updated.csv'
    registrations_file = '/registrations_realistic.csv'
    def load_students(self):
        try:
            with open(self.students_file, "r") as file:
                reader = csv.DictReader(file)
                for row in reader:
                    self.students.append(Student(row["student_id"], row["name"]))
            print("Students loaded!")
        except Exception as e:
            print("Error loading students:", e)

    def load_courses(self):
        try:
            with open(self.courses_file, "r") as file:
                reader = csv.DictReader(file)
                for row in reader:
                    self.courses.append(
                        Course(row["course_id"], row["course_name"], row["credits"])
                    )
            print("Courses loaded!")
        except Exception as e:
            print("Error loading courses:", e)

    def load_registrations(self):
        try:
            with open(self.registrations_file, "r") as file:
                reader = csv.DictReader(file)
                for row in reader:
                    self.registrations.append([row["student_id"], row["course_id"]])
            print("Registrations loaded!")
        except Exception as e:
            print("Error loading registrations:", e)

    def add_student(self):
        sid = input("Enter ID: ")
        name = input("Enter Name: ")
        self.students.append(Student(sid, name))
        print("Student added!")

    def add_course(self):
        cid = input("Enter Course ID: ")
        name = input("Enter Course Name: ")
        credits = input("Enter Credits: ")
        self.courses.append(Course(cid, name, credits))
        print("Course added!")

    def register_course(self):
        sid = input("Student ID: ")
        cid = input("Course ID: ")
        self.registrations.append([sid, cid])
        print("Registered!")

    def drop_course(self):
        sid = input("Student ID: ")
        cid = input("Course ID: ")

        if [sid, cid] in self.registrations:
            self.registrations.remove([sid, cid])
            print("Dropped!")
        else:
            print("Not found!")

    def display_students(self):
        for s in self.students:
            s.display()

    def display_courses(self):
        for c in self.courses:
            c.display()

    def display_registrations(self):
        for r in self.registrations:
            print("Student:", r[0], "-> Course:", r[1])

    def save_data(self):
        try:
            with open("saved_registrations.csv", "w", newline="") as file:
                writer = csv.writer(file)
                writer.writerow(["student_id", "course_id"])
                writer.writerows(self.registrations)
            print("Saved!")
        except Exception as e:
            print("Error saving:", e)

pass

pass

pass

pass

pass

def main():
    system = CourseSystem()

    while True:
        print("\n1.Load Students  2.Load Courses  3.Load Registrations")
        print("4.Add Student    5.Add Course")
        print("6.Register       7.Drop Course")
        print("8.Show Students  9.Show Courses  10.Show Registrations")
        print("11.Save Data     0.Exit")

        choice = input("Choice: ")

        if choice == "1":
            system.load_students()
        elif choice == "2":
            system.load_courses()
        elif choice == "3":
            system.load_registrations()
        elif choice == "4":
            system.add_student()
        elif choice == "5":
            system.add_course()
        elif choice == "6":
            system.register_course()
        elif choice == "7":
            system.drop_course()
        elif choice == "8":
            system.display_students()
        elif choice == "9":
            system.display_courses()
        elif choice == "10":
            system.display_registrations()
        elif choice == "11":
            system.save_data()
        elif choice == "0":
            print("Exiting...")
            break
        else:
            print("Invalid choice!")

main()

